In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('customer.csv')

In [3]:
df.sample(5)

    age  gender   review education purchased
39   76    Male     Poor        PG        No
18   19    Male     Good    School        No
49   25  Female     Good        UG        No
34   86    Male  Average    School        No
11   74    Male     Good        UG       Yes

In [4]:
df = df.iloc[:,2:]

In [5]:
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OrdinalEncoder
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 0:2], df.iloc[:, -1], test_size=0.2, random_state=42)
X_train

In [ ]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])
oe.fit(X_train)

In [ ]:
X_train_enc = oe.transform(X_train)
X_test_enc = oe.transform(X_test)
X_train_enc

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y_train_enc = le.fit_transform(y_train)
y_test_enc = le.transform(y_test)
y_train_enc