In [3]:
import pandas as pd
# just version
pd.__version__
# everything
pd.show_versions()

INSTALLED VERSIONS
------------------
commit                : 2905718b126579d2cf0fe5bae05bd75facb67d77
python                : 3.14.8
python-bits           : 64
OS                    : Windows
OS-release            : 11
Version               : 10.0.26200
machine               : AMD64
processor             : Intel64 Family 6 Model 142 Stepping 10, GenuineIntel
byteorder             : little
LC_ALL                : None
LANG                  : None
LOCALE                : English_United States.1252

pandas                : 3.0.6
numpy                 : 2.5.3
dateutil              : 2.9.0.post0
pip                   : 26.2.1
Cython                : None
sphinx                : None
IPython               : 9.17.1
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : None
bottleneck            : None
fastparquet           : None
fsspec                : None
html5lib              : None
hypothesis            : None
gcsfs                 : None
jinja2                : None
lxml.etree            : None
matplotlib            : None
numba                 : None
numexpr               : None
odfpy                 : None
openpyxl              : 3.1.5
psycopg2              : None
pymysql               : None
pyarrow               : None
pyiceberg             : None
pyreadstat            : None
pytest                : None
python-calamine       : None
pytz                  : None
pyxlsb                : None
s3fs                  : None
scipy                 : None
sqlalchemy            : None
tables                : None
tabulate              : None
xarray                : None
xlrd                  : None
xlsxwriter            : None
zstandard             : None
qtpy                  : None
pyqt5                 : None

Dataframe

In [5]:
import pandas as pd
pd.DataFrame({
    'columns A': [1, 2, 3],
    'columns B': [5, 6, 7],
    'columns c': [9, 10, 11]
    })

   columns A  columns B  columns c
0          1          5          9
1          2          6         10
2          3          7         11

In [9]:
# numpy array use to craete datafram
import numpy as np
arr=np.array([[1, 2,3],[4,5,6],[7,8,9]])
pd.DataFrame(arr)

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [10]:
#random array generate krna
pd.DataFrame(np.random.rand(5,6))

          0         1         2         3         4         5
0  0.461303  0.205401  0.608143  0.783529  0.167730  0.446661
1  0.174700  0.591925  0.181321  0.172984  0.135737  0.775454
2  0.477744  0.058119  0.857659  0.612850  0.713980  0.230606
3  0.650670  0.521266  0.742383  0.860140  0.429650  0.493072
4  0.149698  0.837538  0.699888  0.065104  0.795714  0.578671

In [16]:
#random array generate krna or agr hum column name apni mrzi sy dena chahty h
pd.DataFrame(np.random.rand(5, 6), columns=list('ABCDEF'))

          A         B         C         D         E         F
0  0.593794  0.677983  0.019474  0.761289  0.581749  0.728454
1  0.553529  0.427369  0.575740  0.590368  0.545113  0.784917
2  0.770669  0.643976  0.073256  0.537504  0.731442  0.380922
3  0.378174  0.691911  0.770328  0.210481  0.486936  0.334423
4  0.307001  0.344866  0.247038  0.339373  0.379822  0.291826

In [21]:
# how to rename column names
df=pd.DataFrame({
    'columns A': [1, 2, 3],
    'columns B': [5, 6, 7],
    'columns c': [9, 10, 11]
    })
df #print
df.rename(columns={'columns A': 'col_a', 'columns B': 'col_b'})

   col_a  col_b  columns c
0      1      5          9
1      2      6         10
2      3      7         11